### ISSUE TITLE
--rsync-set-flags and --rsync-append-flags for "--dry-run" is not working

### ISSUE THREAD

**Issue by jesusguevarautomotriz** [basnijholt/rsync-time-machine.py#22]
--rsync-set-flags and --rsync-append-flags for "--dry-run" is not working: error: argument --rsync-set-flags: expected one argument.
![Screenshot 2023-06-09 011032](https://github.com/basnijholt/rsync-time-machine.py/assets/8184794/2eecc323-fe10-4efd-bfee-e20c6fdfb936)

**Comment by basnijholt** [comment]
Hi @jesusguevarautomotriz,

Thanks for reporting!

I see a couple of problems with the command.

You probably want to use `--rsync-append-flags` instead of `--rsync-set-flags` because you will be overwriting the following:
```bash
❯ ./rsync_time_machine.py ~/dotfiles /Volumes/4TB/dotfiles --rsync-set-flags="--dry-run" --rsync-get-flags
rsync-time-machine.py: Rsync flags:
--dry-run
```
vs
```bash
❯ ./rsync_time_machine.py ~/dotfiles /Volumes/4TB/dotfiles --rsync-append-flags="--dry-run" --rsync-get-flags
rsync-time-machine.py: Rsync flags:
-D --numeric-ids --links --hard-links --one-file-system --itemize-changes --times --recursive --perms --owner --group --stats --human-readable --dry-run
```
Then you need an equals sign in your command:
```bash
--rsync-append-flags="--dry-run"
```

**Comment by jesusguevarautomotriz** [comment]
It is my mistake. Thank you very much for the explanation, I will try the script again.
