### ISSUE TITLE
Script execution error on destination folder containing the name of the script folder.

### ISSUE THREAD

**Issue by jesusguevarautomotriz** [basnijholt/rsync-time-machine.py#30]
Hi,
Context:
I do git clone https://github.com/basnijholt/rsync-time-machine.py.git >> I rename folder to **rtmpy**. Also rename the script to **rtm.py**.

There are several scripts similar to this that I'm testing, they all contain the term _rsync_ in the name, so I shorten the name to its initial letters to differentiate between them and to be able to do separate searches of the bash history of any _rsync_-based scripts and of the program _rsync_.

But also at the end of the path of the destination folder I put the name of the folder that contains the script:
**rtmpy**: script folder.
backup/x/y/z/2023-07-17_**rtmpy**
So I can khow very quickly at a glance and without opening the directory with which script that backup was made.

I suspect that doing this results in an error.

The original directory that I intend to back up, containing the name **rtmpy** in its path.

```console
user02@AsusVivoBookX712JA ~/rtmpy                      
$ ./rtm.py /cygdrive/c/Docs user04@asusx750jbku23:/media/user04/Expansion/Backups_Live/Personal/003-Laptop-AsusVivoBookX712JA-212_V17WN/2023-06-25_**rtmpy**/ rsync-append-flags="--dry-run"                                      
Traceback (most recent call last):                     
  File "/home/user02/rtmpy/./rtm.py", line 925, in <module>                                                    
    main()                 
  File "/home/user02/rtmpy/./rtm.py", line 907, in main                                                        
    backup(                
  File "/home/user02/rtmpy/./rtm.py", line 828, in backup                                                      
    handle_still_running_or_failed_or_interrupted_backup(                                                      
  File "/home/user02/rtmpy/./rtm.py", line 656, in handle_still_running_or_failed_or_interrupted_backup        
    exit_if_pid_running(running_pid, ssh)              
  File "/home/user02/rtmpy/./rtm.py", line 630, in exit_if_pid_running                                         
    if running_cmd.returncode == 0:                    
AttributeError: 'str' object has no attribute 'returncode'                                                     

user02@AsusVivoBookX712JA ~/rtmpy                      
$                          
```

Making the change (o delete) of one letter, I get the expected result.
```console
user02@AsusVivoBookX712JA ~/rtmpy                      
$ ./rtm.py /cygdrive/c/Docs user04@asusx750jbku23:/media/user04/Expansion/Backups_Live/Personal/003-Laptop-AsusVivoBookX712JA-212_V17WN/2023-06-25_rtmp/ rsync-append-flags="--dry-run"                                       
rsync-time-machine.py: Safety check failed - the destination does not appear to be a backup folder or drive (marker file not found).      
rsync-time-machine.py: If it is indeed a backup folder, you may add the marker file by running the following command:                     
rsync-time-machine.py: ssh -p 22 user04@asusx750jbku23 'mkdir -p -- "/media/user04/Expansion/Backups_Live/Personal/003-Laptop-AsusVivoBookX712JA-212_V17WN/2023-06-25_rtmp" ; touch "/media/user04/Expansion/Backups_Live/Personal/003-Laptop-AsusVivoBookX712JA-212_V17WN/2023-06-25_rtmp/backup.marker"'                                   

user02@AsusVivoBookX712JA ~/rtmpy                      
$                          
```

![Screenshot 2023-07-17 231541](https://github.com/basnijholt/rsync-time-machine.py/assets/8184794/2a3af701-2d4f-45ff-a420-8ebd26008e6f)
Thank you.

**Comment by basnijholt** [comment]
I see the issue! Thanks for reporting. I fixed this issue in https://github.com/basnijholt/rsync-time-machine.py/commit/da048c241a6e99e5b022d9fcd1397b8e0aee3d46.

Unfortunately, I have no access to a Cygwin machine and there is no CI that is readily available where I can test it on.

Could you try again

**Comment by basnijholt** [comment]
You are also missing the `--` in `--rsync-append-flags` BTW

**Comment by jesusguevarautomotriz** [comment]
After test:
```console
rsync-time-machine.py: Backup completed without errors. 
```
It works. Thank you for all..!

**Comment by basnijholt** [comment]
Glad it now works! 😄
